enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
patches-version = "latest" # TODO: remove after new build / fix
# patches-version = "dev"
cli-version = "dev"
remove-rv-integrations-checks = false # Patching revanced-integrations failed

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# dont build on gh actions (https://github.com/j-hc/revanced-magisk-module/issues/554)
[Music-Extended]
enabled = true
app-name = "Music"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
build-mode = "both"
arch = "arm64-v8a"
patcher-args = "-e \"Spoof client\""
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
build-mode = "both"
arch = "all"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
